NUM_WORKERS: 0
VECTORIZE_AND_SAVING: True
LOAD_LOCAL_CSV: True
SPLIT_DATA: True
GLOBAL_BATCH_SIZE: 500
LOCAL_BATCH_SIZE: 4096
AE_TRAINING_BATCH_SIZE: 512
TEST_SIZE: 0.11
INPUT_SHAPE: 67*32
HIDDEN_EMB_SIZE: 64
MONITOR_LOSS: "val_loss"
PL_TRAINER_MODE: "min"
PL_TRAINER_VERBOSE: True
EARLY_STOP_PATIENCE: 5
MIN_DELTA: 0.001
MAX_EPOCHS: 100
CHECKPOINT_ROOT_DIR: 'tsms_bin_data/compress_ae_checkpoints'
AUTO_LR_FIND: True
BENCHMARK: True
DETERMINISTIC: True
LOG_EVERY_N_STEPS: 1
MAX_ITER_TRAIN_TENSORS_SAVING_COUNT: 250
SAVE_LAST: False
WEIGHT_CLASS_TENSOR_JSON_PATH: 'tsms_bin_data/weight_tensors.json'
TRAIN_TENSORS_PATH: 'tsms_bin_data/train_tensors/generated_train_tensors.pt'
