NUM_WORKERS: 0
VECTORIZE_AND_SAVING: True
LOAD_LOCAL_CSV: True
SPLIT_DATA: True
GLOBAL_BATCH_SIZE: 500
LOCAL_BATCH_SIZE: 4096
AE_TRAINING_BATCH_SIZE: 512
TEST_SIZE: 0.11
HIDDEN_EMB_SIZE: 64
MONITOR_LOSS: "val_loss"
PL_TRAINER_MODE: "min"
PL_TRAINER_VERBOSE: True
EARLY_STOP_PATIENCE: 8
MIN_DELTA: 0.001
MAX_EPOCHS: 1000
CHECKPOINT_ROOT_DIR: 'raw_bin_data/raw_ae_checkpoints/'
AUTO_LR_FIND: True
BENCHMARK: True
DETERMINISTIC: True
LOG_EVERY_N_STEPS: 1
MAX_ITER_COUNT: 11
TRAIN_SIZE: 1500000
MAX_LOAD_CTNS_COUNT: 50000000
CLICKHOUSE_LOAD_BATCH_SIZE: 50000
DROPNA: False
DROP_SUBS_KEYS_COLUMN: True
GENERATE_NEW_TRAIN_AE_DATA: False
RAW_AE_TRAINING: True
SAVE_LAST: True
INPUT_SHAPE: 406 #323
SCALER_PATH: 'raw_bin_data/scaler/std_scaler_ae.bin'
TRAIN_DATA_TENSOR_PATH: 'raw_bin_data/train_tensors/vecs_users_raw_ae_train.pt'
#USER_EMBED_BINFILE_PATH: 'raw_bin_data/raw_lal_23112022_dim64.bin'
